FROM apache/airflow:2.9.2-python3.12

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY airflow_requirements.txt /tmp/airflow_requirements.txt
RUN chown airflow: /tmp/airflow_requirements.txt

USER airflow
RUN pip install --no-cache-dir -r /tmp/airflow_requirements.txt && rm /tmp/airflow_requirements.txt