services:
  # -------------------------------------
  # PostgreSQL
  # -------------------------------------
  postgres:
    image: postgres:17
    container_name: psql_source
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #       restart: true

  # -------------------------------------
  # ClickHouse
  # -------------------------------------
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ch_analytics
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      # Mount our custom user configuration to allow remote connections
      - ./clickhouse_config/users.xml:/etc/clickhouse-server/users.d/default-user-access.xml
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      retries: 5

  # -------------------------------------
  # Airflow
  # -------------------------------------
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    environment:
      # Airflow Core Configuration
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      # Airflow Database Connection (using the existing Postgres service)
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
      # The following variables are used by the entrypoint to initialize the DB and create a user
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USER:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD:-admin}
      # Define connections using Airflow's standard environment variable format.
      # These will be automatically created on startup.
      AIRFLOW_CONN_CLICKHOUSE_DEFAULT: "clickhouse://${CLICKHOUSE_USER:-default}:${CLICKHOUSE_PASSWORD:-}@${CLICKHOUSE_HOST:-clickhouse}:9000/default"
      AIRFLOW_CONN_POSTGRES_SOURCE: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:5432/${POSTGRES_DB:-postgres}"
    volumes:
      - ./dags:/opt/airflow/dags
      # Mount the SQL directory as a volume to ensure local changes are reflected instantly.
      - ./pipeline:/opt/airflow/pipeline
      - ./tests:/opt/airflow/tests
    ports:
      # Map to a different host port (e.g., 8081) to avoid common conflicts on Windows.
      - "8081:8080"
    command: standalone
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  # -------------------------------------
  # Flyway Migrations
  # -------------------------------------
  flyway:
    image: flyway/flyway
    container_name: db_migrations
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./migrations/:/flyway/sql
    environment:
      FLYWAY_CONNECT_RETRIES: 10

volumes:
  postgres_data:
  clickhouse_data:
